# Generated by Django 3.2.5 on 2022-04-03 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='POrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
                ('transaction_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.customer')),
            ],
            options={
                'db_table': 'p_order',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.shop')),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.shop')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('contains_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.porder')),
            ],
            options={
                'db_table': 'contains',
            },
        ),
    ]
