# Generated by Django 3.2.5 on 2022-04-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contains',
            name='contains_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='porder',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
