# Generated by Django 3.2.5 on 2022-04-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0004_auto_20220403_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['type', 'breed', 'age']},
        ),
    ]
