# Generated by Django 3.2.5 on 2022-04-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0005_alter_pet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='recommender_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
