# Generated by Django 3.2.5 on 2022-04-29 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0006_auto_20220428_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porder',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='porder',
            name='transaction_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
